name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Dear ImGui version tag'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ./release.sh ${{ github.event.inputs.version }}
