name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Dear ImGui version tag'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Generate
        run: |
          ./release.sh ${{ github.event.inputs.version }}
      - name: Commit & Push
        run: |
          git config --global user.name "GH Action"
          git config --global user.email "none"
          git add .
          git commit -m "updated (${{ github.event.inputs.version }})"
          git tag ${{ github.event.inputs.version }}
          git push && git push --tags
